create table if not exists public.encuentros (
  id bigserial primary key,
  nombre text not null unique,
  slug text not null unique,
  numero integer,
  ciudad text,
  provincia text,
  fecha text,
  horario text,
  lugar text,
  direccion text,
  maps_url text,
  imagen_url text,
  whatsapp_url text,
  descripcion text,
  ingreso_solidario text,
  cupo integer,
  activo boolean not null default true,
  certificado_activo boolean not null default true,
  mail_opcional boolean not null default false,
  asociado_opcional boolean not null default false,
  celular_obligatorio boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists encuentros_slug_idx on public.encuentros (slug);

insert into public.encuentros (
  nombre,
  slug,
  numero,
  ciudad,
  provincia,
  fecha,
  horario,
  lugar,
  direccion,
  maps_url,
  imagen_url,
  descripcion,
  ingreso_solidario,
  mail_opcional,
  asociado_opcional,
  celular_obligatorio
) values
  (
    'Bahia Blanca 11/3',
    'bahia-blanca-11-3',
    27,
    'Bahia Blanca',
    'Buenos Aires',
    '11/03/2026',
    '14:00 hs',
    'Cam. de la Carrindanga 3802',
    'Cam. de la Carrindanga 3802, B8000 Bahia Blanca',
    'https://share.google/viNow9oZuZHkSdo9C',
    '/Prueba_2/assets/bahia-blanca.jpg',
    'Inscripcion abierta para el encuentro en Bahia Blanca.',
    'Traer uno o dos alimentos no perecederos para donar a una institucion de la zona',
    true,
    false,
    false
  ),
  (
    'Mar del Plata 14/3',
    'mar-del-plata-14-3',
    28,
    'Mar del Plata',
    'Buenos Aires',
    '14/03/2026',
    '08:30 hs',
    'Av. Pedro Luro 8851',
    'Av. Pedro Luro 8851, B7606 Mar del Plata',
    'https://share.google/KA62Zn0H6wtiLd0La',
    '/Prueba_2/assets/mar-del-plata.webp',
    'Inscripcion abierta para el encuentro en Mar del Plata.',
    'Traer uno o dos alimentos no perecederos para donar a una institucion de la zona',
    true,
    false,
    false
  ),
  (
    'Mendoza 9/5',
    'mendoza-9-5',
    29,
    'Mendoza',
    'Mendoza',
    '09/05/2026',
    '08:00 a 16:30 hs',
    'Espacio Cultural Julio Le Parc',
    'Mitre y Godoy Cruz, Guaymallen, Mendoza',
    'https://maps.app.goo.gl/Y49wHh722F2bY6uJ8',
    '/Prueba_2/assets/mendoza.jpg',
    'Encuentro tecnico para plomeros y sanitaristas.',
    'Ingreso solidario: para participar del evento, es necesario llevar 2 alimentos no perecederos.',
    true,
    true,
    false
  ),
  (
    'Salta 6/6',
    'salta-6-6',
    30,
    'Salta',
    'Salta',
    '06/06/2026',
    '08:30 hs',
    'Club Social Ahorrarte',
    'Club Social Ahorrarte, Salta',
    'https://maps.app.goo.gl/sHd5dqsa6RnW2hws6',
    '/Prueba_2/assets/salta.jpg',
    'Encuentro tecnico para plomeros y sanitaristas.',
    'Ingreso solidario: para participar del evento, es necesario llevar 2 alimentos no perecederos.',
    true,
    false,
    false
  ),
  (
    'San Luis 8/8',
    'san-luis-8-8',
    31,
    'Villa Mercedes',
    'San Luis',
    '07 y 08/08/2026',
    'Viernes: 16:00-21:00 | Sabado: 09:00-18:00',
    'UPrO de Villa Mercedes',
    'UPrO de Villa Mercedes',
    'https://share.google/7T00qtcB1UeGZJfir',
    '/Prueba_2/assets/san-luis.png',
    'Inscripcion abierta para el encuentro en San Luis.',
    'Ingreso solidario: para participar del evento, es necesario llevar 2 alimentos no perecederos.',
    false,
    false,
    true
  )
on conflict (slug) do update set
  nombre = excluded.nombre,
  numero = excluded.numero,
  ciudad = excluded.ciudad,
  provincia = excluded.provincia,
  fecha = excluded.fecha,
  horario = excluded.horario,
  lugar = excluded.lugar,
  direccion = excluded.direccion,
  maps_url = excluded.maps_url,
  imagen_url = excluded.imagen_url,
  descripcion = excluded.descripcion,
  ingreso_solidario = excluded.ingreso_solidario,
  mail_opcional = excluded.mail_opcional,
  asociado_opcional = excluded.asociado_opcional,
  celular_obligatorio = excluded.celular_obligatorio,
  updated_at = now();
